site_name: TEK Documentation
site_description: Documentation on Different Tech Stacks
repo_url: https://github.com/Sandy1101/tech-docs
edit_url: blob/main/docs/
docs_dir: docs

nav:
  - TechStack:
    - techstack/index.md
    - Backstage:
      - backstage/index.md
      - backstage/overview.md
    - WebMethods:
      - webmethods/index.md
plugins:
  - search
  - techdocs-core
